dataset_configs:
  desc: Dataset Configurations
  value:
    base_dataset_path: "./dataset/" # LOCAL
    # base_dataset_path: "/content/drive/MyDrive/Programming/dataset/" # GOOGLE COLAB
    plantpathology: "plantpathology"
    stanfordcars: "stanfordcars"
    flowers102: "flowers102"
    dtd: "dtd"

training_hyperparameters:
  desc: Training Hyperparameters
  value:
    batch_size: 32
    num_epochs: 25
    learning_rate: 0.001
    weight_decay: 0.0001
    warmup_steps: 4000

experiment_details:
  desc: Experiment Details
  value:
    model_dir: "./trained_models/"
    experiment_name: "e1_baseline"
    use_wandb: True

plant_label_encoding:
  desc: Plant Label Encoding
  value:
    "healthy": 0
    "scab": 1
    "rust": 2
    "frog_eye_leaf_spot": 3
    "powdery_mildew": 4

wandb_config:
  desc: Weights and Biases Configuration
  value:
    project: "OOD_Exploration"
    entity: "deveshshah-university-of-michigan"
    mode: "online"
    config: {}
